export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const ENTITY_FAILURE = 'ENTITY_FAILURE';
export const ENTITY_CREATE = 'ENTITY_CREATE';
export const ENTITY_UPDATE = 'ENTITY_UPDATE';
export const ENTITY_FETCH = 'ENTITY_FETCH';
export const ENTITY_DELETE = 'ENTITY_DELETE';
export const SELECT_ENTITY_ITEM = 'SELECT_ENTITY_ITEM';
export const CLEAR_ENTITY_LIST = 'CLEAR_ENTITY_LIST';

export const IMAGE_URL_RETURNED = 'IMAGE_URL_RETURNED';
export const IMAGE_PROCESSING = 'IMAGE_PROCESSING'; 
export const IMAGE_PROCESS_ERROR = 'IMAGE_PROCESS_ERROR';
export const SERVER_NUMBER_IMAGE_PROCESSING = 'SERVER_NUMBER_IMAGE_PROCESSING';
export const IMG_PREVIEW = 'IMG_PREVIEW';
export const JOB_RETRYING = 'JOB_RETRYING';
export const NOTIFICATION_SHOWED = 'NOTIFICATION_SHOWED';
export const MESSAGE = 'MESSAGE';
export const FILE_CHOSEN = 'FILE_CHOSEN';
export const SHOW_RESULT_PAGE = 'SHOW_RESULT_PAGE';
export const IMAGE_UPLOADING = 'IMAGE_UPLOADING';
export const RESET_FILE_CHOSEN = 'RESET_FILE_CHOSEN';

export const REDUX_LOCATION_CHANGE = '@@router/LOCATION_CHANGE';